version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.4-node-browsers
        environment:
          DB_HOST: 127.0.0.1
          TZ: /usr/share/zoneinfo/Asia/Tokyo
      - image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    steps:
      - checkout
      - restore_cache:
          name: Restore bundle cache
          keys:
              - bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Run bundle install
          command: bundle install --path=vendor/bundle
      - save_cache:
          name: Store bundle cache
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
              - vendor/bundle
      - run:
          name: Run db create
          command: |
              bundle exec rake db:create
              bundle exec rake db:schema:load
      - run:
          name: Run RSpec
          command: bundle exec rspec
