development:
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  database: qryption_development

test:
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  database: qryption_test

production:
  host: qryption-aurora.cbbaeukougsd.ap-northeast-1.rds.amazonaws.com
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /tmp/mysql.sock
  database: qryption_db
  username: qryption_db
  password: <%= ENV['QRYPTION_DATABASE_PASSWORD'] %>
